<a href="https://colab.research.google.com/github/vhvaldiviesor/Programacion-para-analitica-descriptiva-y-predictiva/blob/main/S06_Actividad_02_ALGEBRALINEAL_45210.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**
Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

**Nombre completo:** Victor Hugo Valdivieso Rodriguez  
**Matrícula:** 45210

---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [5]:
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [6]:
norma_A = np.linalg.norm(producto_A)
norma_B = np.linalg.norm(producto_B)
norma_C = np.linalg.norm(producto_C)

print("Norma producto_A:", norma_A)
print("Norma producto_B:", norma_B)
print("Norma producto_C:", norma_C)


Norma producto_A: 7.449161026585477
Norma producto_B: 6.777167549942971
Norma producto_C: 5.238320341483518


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [7]:
# 1. Producto punto
dot_AB = np.dot(producto_A, producto_B)
dot_AC = producto_A @ producto_C
print("A·B:", dot_AB)
print("A·C:", dot_AC)

# 2. Ángulo en grados a partir del coseno del ángulo
coseno_AB = dot_AB / (norma_A * norma_B)
coseno_AC = dot_AC / (norma_A * norma_C)
angulo_AB = np.degrees(np.arccos(coseno_AB))
angulo_AC = np.degrees(np.arccos(coseno_AC))
print("Ángulo A-B (grados):", angulo_AB)
print("Ángulo A-C (grados):", angulo_AC)

# 3. El producto B es más similar a A: su ángulo (~1.8°) es mucho menor que el de C (~47.2°).
# El ángulo es el indicador correcto porque mide la similitud en la "dirección" del vector
# (proporción entre calidad, precio y servicio) sin que la magnitud de las calificaciones
# distorsione la comparación.


A·B: 50.46
A·C: 26.5
Ángulo A-B (grados): 1.7745815839558179
Ángulo A-C (grados): 47.22509268261831


---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [8]:
unitario_A = producto_A / norma_A
unitario_B = producto_B / norma_B
unitario_C = producto_C / norma_C

print("Vector unitario A:", unitario_A, "- norma:", np.linalg.norm(unitario_A))
print("Vector unitario B:", unitario_B, "- norma:", np.linalg.norm(unitario_B))
print("Vector unitario C:", unitario_C, "- norma:", np.linalg.norm(unitario_C))


Vector unitario A: [0.60409488 0.42957858 0.67121653] - norma: 1.0
Vector unitario B: [0.59021707 0.41315195 0.69350506] - norma: 1.0
Vector unitario C: [0.19090089 0.95450444 0.22908106] - norma: 1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [9]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [10]:
# 1. Producto elemento a elemento vs multiplicación matricial
M_por_P_elemento = M * P
M_por_P_matricial = M @ P
print("M * P (elemento a elemento):\n", M_por_P_elemento)
print("M @ P (matricial):\n", M_por_P_matricial)

# Son distintos porque M * P multiplica cada posición (i, j) de M con la misma posición
# de P, mientras que M @ P calcula, para cada posición, la suma de productos de una fila
# de M con una columna de P (la multiplicación matricial estándar).

# 2. P @ M vs M @ P
P_por_M = P @ M
print("P @ M:\n", P_por_M)
print("¿M @ P es igual a P @ M?:", np.array_equal(M_por_P_matricial, P_por_M))
# No da el mismo resultado: la multiplicación matricial no es conmutativa.


M * P (elemento a elemento):
 [[3. 0.]
 [0. 6.]]
M @ P (matricial):
 [[3.  2. ]
 [1.5 6. ]]
P @ M:
 [[3.  1.5]
 [2.  6. ]]
¿M @ P es igual a P @ M?: False


---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [11]:
# 1. Determinante
det_M = np.linalg.det(M)
print("Determinante de M:", det_M)
print("¿M tiene inversa? (det != 0):", det_M != 0)

# 2. Inversa
M_inv = np.linalg.inv(M)
print("Inversa de M:\n", M_inv)

# 3. Verificación: M @ M_inv debe ser (aprox.) la matriz identidad
verificacion = M @ M_inv
print("M @ M_inv:\n", verificacion)


Determinante de M: 5.000000000000001
¿M tiene inversa? (det != 0): True
Inversa de M:
 [[ 0.6 -0.2]
 [-0.2  0.4]]
M @ M_inv:
 [[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [12]:
b = np.array([180, 300])

# 1. Resolver el sistema M x = b
x = np.linalg.solve(M, b)
print("Solución x:", x)

# 2. Verificación
verificacion = M @ x
print("M @ x:", verificacion)
print("¿Coincide con b?:", np.allclose(verificacion, b))


Solución x: [48. 84.]
M @ x: [180. 300.]
¿Coincide con b?: True


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [13]:
# 1. Distancia euclidiana
distancia_AB = np.linalg.norm(producto_A - producto_B)
distancia_AC = np.linalg.norm(producto_A - producto_C)
print("Distancia euclidiana A-B:", distancia_AB)
print("Distancia euclidiana A-C:", distancia_AC)

# 2. Similitud coseno (ya calculada en el Ejercicio 2, antes de aplicar arccos)
similitud_AB = coseno_AB
similitud_AC = coseno_AC
print("Similitud coseno A-B:", similitud_AB)
print("Similitud coseno A-C:", similitud_AC)

# 3. Conclusión
if distancia_AB < distancia_AC and similitud_AB > similitud_AC:
    conclusion = "producto_B es más parecido a producto_A: tiene menor distancia euclidiana y mayor similitud coseno. Ambas métricas coinciden."
else:
    conclusion = "Las métricas no coinciden en la misma conclusión."

print(conclusion)


Distancia euclidiana A-B: 0.7071067811865476
Distancia euclidiana A-C: 5.470831746635972
Similitud coseno A-B: 0.9995203969214979
Similitud coseno A-C: 0.6791199021706347
producto_B es más parecido a producto_A: tiene menor distancia euclidiana y mayor similitud coseno. Ambas métricas coinciden.


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.